// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9BYy-GxImWk7MmyW7WA_-FRuPG45u6xo',
    appId: '1:597032682509:android:6c7e18ccec8ca7df918144',
    messagingSenderId: '597032682509',
    projectId: 'dr-nada-68e71',
    databaseURL: 'https://dr-nada-68e71-default-rtdb.firebaseio.com',
    storageBucket: 'dr-nada-68e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6LpEOM8afzcTS8bktuHQrSjkJfASGzYY',
    appId: '1:597032682509:ios:4c000e4874a1ef9c918144',
    messagingSenderId: '597032682509',
    projectId: 'dr-nada-68e71',
    databaseURL: 'https://dr-nada-68e71-default-rtdb.firebaseio.com',
    storageBucket: 'dr-nada-68e71.firebasestorage.app',
    iosBundleId: 'com.example.drNadaSalmaMedEduPlat',
  );
}
